### ISSUE TITLE
UI update on background thread

### ISSUE THREAD

**Issue by NutanNiraula** [hoangtoro102/NimbleSurvey#1]
@hoangtoro102 Hi, it is great to meet you here through the review process. I would like to raise some issues to better understand your decisions. Please fix those that you think are important creating appropriate branches and following proper gitflow and/or provide some additional context or ideas to justify the decisions you made. I would like to start with a thread issue. Could you please find the root cause and fix it in app?

![screenshot](https://i.imgur.com/i8kMZEu.png)

**Comment by hoangtoro102** [comment]
Thanks for your feedback. I fixed it on commit: https://github.com/hoangtoro102/NimbleSurvey/commit/3339ddda465ceee2941c35bdd3880777657fd8ed
