### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by NutanNiraula** [hoangtoro102/NimbleSurvey#2]
Here are some of the UI issues that I noticed

1. It seems you have not handled the safe area well, there is a white bar below the collectionView in notched devices
2. Do you think it would be beneficial to add a tinted overlay below the title text? because in bright background title is not visible.
3. Navigation bar is implemented using custom view. Do you think using native navigation bar component would help us scale the app better? The navigation bar and status bar colors do not match and buttons have blue tint.
4. App crashes on scrolling on the last page. Could you please check it?

**Comment by hoangtoro102** [comment]
Thanks, I found the issues and fixed on [0f9ee1f
](https://github.com/hoangtoro102/NimbleSurvey/commit/0f9ee1fe8cbebf2f9bfa1055f64c95507fbc86ea) . Please take a look.
