### ISSUE TITLE
Unit tests issues

### ISSUE THREAD

**Issue by NutanNiraula** [hoangtoro102/NimbleSurvey#3]
@hoangtoro102 Hi, I found that lot of your tests are failing. Could you please look into this?

![screenshot](https://i.imgur.com/UPF9gQU.png)

Also, I saw that you are running performance tests in unit test and launch speed tests in UI test. Do you think we should remove the excess code in unit test files that we are not using? And for UI tests, do you think it can have any negative impact on the CI or automation process?

**Comment by hoangtoro102** [comment]
Hi @NutanNiraula, thanks for your feedback.
I have updated these failing unit tests and remove unused tests as well. https://github.com/hoangtoro102/NimbleSurvey/commit/505843b2a4ef739946a7ed478b531d9bcf60efbe
For UI tests, I also implemented some simple tests. https://github.com/hoangtoro102/NimbleSurvey/commit/6eaad67cffc9d8d0efd643b7e8527f03f2ae0156

Please take a look.

**Comment by NutanNiraula** [comment]
@hoangtoro102 Thanks for the submission, 🎉  our team will be reviewing the code and providing the decision within few days. It was great to go through the review process with you. Wish you all the best. 🍀
